export const Images = {
	//-- Img Yschool

	icLinkVideo: require('./imgApp/icLinkVideo.png'),

	linkicon: require('./imgApp/linkicon.png'),
	logoSSC: require('./imgApp/logoSSC.png'),
	bgYSchool: require('./imgApp/bgYSchool.png'),
	bgYSSplashScreen: require('./imgApp/icBgrLoading.png'),
	logoYSchool: require('./imgApp/logoYSchool.png'),
	bgLogin: require('./imgApp/bgLogin.png'),
	bgChat: require('./imgApp/bgChat.png'),
	bgBaoBai: require('./imgApp/bgBaoBai.png'),
	bgHocPhi: require('./imgApp/bgHocPhi.png'),
	bgDiemDanh: require('./imgApp/bgDiemDanh.png'),
	icMenu1: require('./imgApp/icMenu1.png'),
	icBell1: require('./imgApp/icBell1.png'),

	icNotifycation1: require('./imgApp/icNotifycation1.png'),
	iconMail1: require('./imgApp/iconMail1.png'),
	icThpiKhoaBieu1: require('./imgApp/icThpiKhoaBieu1.png'),
	icKetQuaHocTam1: require('./imgApp/icKetQuaHocTam1.png'),
	iconNext1: require('./imgApp/iconNext1.png'),
	icCaiDat1: require('./imgApp/icCaiDat1.png'),
	icHome: require('./imgApp/icHome.png'),
	icManUser: require('./imgApp/icManUser.png'),
	icExit1: require('./imgApp/icExit1.png'),
	imgProfile: require('./imgApp/avatarBig.png'),
	icHomeDd: require('./imgApp/icHomeDd.png'),
	icHomeDdAn: require('./imgApp/icHomeDdAn.png'),
	icHomeBaoBai: require('./imgApp/icHomeBaoBai.png'),
	icHomeChat: require('./imgApp/icHomeChat.png'),

	icHocPhi: require('./imgApp/icHocPhi.png'),
	icThuChi: require('./imgApp/icThuChi.png'),
	icBackWhite: require('./imgApp/icBackWhite.png'),

	// bgLogin
	//--component
	Group: require('./imgApp/group.png'),
	icCameraBlack: require('./imgApp/icCameraBlack.png'),
	icCheckboxWhite: require('./imgApp/icCheckboxWhite.png'),
	icChooseItemGreen: require('./imgApp/icChooseItemGreen.png'),
	icCloseGrey: require('./imgApp/icCloseGrey.png'),
	icCloseWhite: require('./imgApp/icCloseWhite.png'),
	icFeedRed: require('./imgApp/icFeedRed.png'),
	icLocationBlack: require('./imgApp/icLocationBlack.png'),
	icPhotoBlack: require('./imgApp/icPhotoBlack.png'),
	icSearchGrey: require('./imgApp/icSearchGrey.png'),
	icRecordVideo: require('./imgApp/icRecordVideo.png'),
	icCameraSwitchWhite: require('./imgApp/icCameraSwitchWhite.png'),
	icCaptureImage: require('./imgApp/icCaptureImage.png'),
	icVideoBlack: require('./imgApp/icVideoBlack.png'),
	icVideoRecording: require('./imgApp/icVideoRecording.png'),
	icForward: require('./imgApp/icForward.png'),
	icFullScreen: require('./imgApp/icFullScreen.png'),
	icPause: require('./imgApp/icPause.png'),
	icPlay: require('./imgApp/icPlay.png'),
	icRewind: require('./imgApp/icRewind.png'),
	icCloseBlack: require('./imgApp/icCloseBlack.png'),
	iconUserGray: require('./imgApp/icUserGray.png'),
	icSendMsg: require('./imgApp/icSendBig.png'),

	//-- Img Component
	mediaPlayButton: require('./imgComponent/mediaPlayButton.png'),
	icLineRight: require('./imgComponent/icLineRight.png'),
	icCalendarPicker: require('./imgComponent/icCalendarPicker.png'),

	//-- TripU
	icTripU: require('./imgApp/icTripU.png'),
	icTripUBig: require('./imgApp/icTripUBig.png'),
	icTripU2: require('./imgApp/icTripU2.png'),
	icUser: require('./imgApp/icUser.png'),
	icUserGroup: require('./imgApp/icUserGroup.png'),
	icCalendar: require('./imgApp/icCalendar.png'),
	icHotels: require('./imgApp/icHotels.png'),
	icFlight: require('./imgApp/icFlight.png'),
	icMyLocation: require('./imgApp/myLocation.png'),
	// AboutUS: require('./imgApp/AboutUS.jpeg'),
	icTelephone: require('./imgApp/icTelephone.png'),
	icThumbsUp: require('./imgApp/icThumbsUp.png'),
	icPrinter: require('./imgApp/icPrinter.png'),

	icOutlineExitToApp: require('./imgApp/outline-exit-to-app.png'),
	icFavorite: require('./imgApp/outline-favorite.png'),
	icUnfavorite: require('./imgApp/outline-unfavorite.png'),
	icMinus: require('./imgApp/minus.png'),
	icStarYellow: require('./imgApp/icStarYellow.png'),
	icStarWhite: require('./imgApp/icStarWhite.png'),
	icStarWhiteEmpty: require('./imgApp/icStarWhiteEmpty.png'),
	icDropDown: require('./imgApp/icDropDown.png'),
	icEdit: require('./imgApp/icEdit.png'),
	icCheckBlue: require('./imgApp/icCheckBlue.png'),
	icSwimming: require('./imgApp/icSwimming.png'),
	icBackBlue: require('./imgApp/icBackBlue.png'),
	icNext: require('./imgApp/icNext.png'),
	icVali: require('./imgApp/icVali.png'),
	icMail: require('./imgApp/icMail.png'),
	icSecurity: require('./imgApp/icSecurity.png'),
	icVisa: require('./imgApp/icVisa.png'),
	icLock: require('./imgApp/icLock.png'),
	imgFlight: require('./imgApp/imgFlight.png'),
	imgCar: require('./imgApp/imgCar.png'),
	icTimeTick: require('./imgApp/icTimeTick.png'),
	icTopHotels: require('./imgApp/icTopHotels.png'),
	icPonits: require('./imgApp/icPonits.png'),
	icTimeTickRed: require('./imgApp/icTimeTickRed.png'),
	icBell: require('./imgApp/icBell.png'),
	icStarWhite: require('./imgApp/icStarWhite.png'),
	icRestaurants: require('./imgApp/icRestaurants.png'),
	icSignature: require('./imgApp/icSignature.png'),
	icInOut: require('./imgApp/icInOut.png'),
	// icAirAsia: require('./imgApp/icAirAsia.png'),
	icVali: require('./imgApp/icVali.png'),
	icPlay: require('./imgApp/icPlay.png'),
	// icAirplaneflight: require('./imgApp/icAirplaneflight.png'),
	icMoon: require('./imgApp/icMoon.png'),
	icValiPlus: require('./imgApp/icValiPlus.png'),
	icLogoVNAirLine: require('./imgApp/iclogoVnaMobile.png'),
	icSubtraction: require('./imgApp/icSubtraction.png'),
	// icAirplaneflightOut: require('./imgApp/icAirplaneflightOut.png'),
	icShuffle: require('./imgApp/icShuffle.png'),
	icRefund: require('./imgApp/icRefund.png'),
	icWifi: require('./imgApp/icWifi.png'),
	LogoTripU: require('./imgApp/tripULogo.png'),
	icU: require('./imgApp/icU.png'),
	logoTripUWhite: require('./imgApp/logoTripUWhite.png'),
	logoTripAdvisor: require('./imgApp/logoTripAdvisor.png'),
	icbackspace: require('./imgApp/icbackspace.png'),
	icfavoriteborder: require('./imgApp/icfavoriteborder.png'),
	icpercent: require('./imgApp/icpercent.png'),
	icmorevert: require('./imgApp/icmorevert.png'),
	icbed: require('./imgApp/icbed.png'),
	icinfo: require('./imgApp/icinfo.png'),
	icdone: require('./imgApp/icdone.png'),
	icdola: require('./imgApp/icdola.png'),
	icglass: require('./imgApp/icglass.png'),
	icoutlineverified: require('./imgApp/icoutlineverified.png'),
	ichotel2: require('./imgApp/ichotel2.png'),
	// icroundEventNote: require('./imgApp/roundEventNote.png'),
	icpostoffice: require('./imgApp/icpostoffice.png'),
	ickeyboardbackspace: require('./imgApp/ickeyboardbackspace.png'),
	ichangkhong: require('./imgApp/ichangkhong.png'),
	ictourdulich: require('./imgApp/ictourdulich.png'),
	ickhachsanHome: require('./imgApp/ickhachsanHome.png'),
	icvisadulich: require('./imgApp/icvisadulich.png'),
	icblogdulich: require('./imgApp/icblogdulich.png'),
	icxemthem: require('./imgApp/icxemthem.png'),
	ictourguide: require('./imgApp/ictourguide.png'),
	icvidientucir: require('./imgApp/icViDienTuCir.png'),
	icVA: require('./imgApp/icVA.png'),
	ictextsms: require('./imgApp/ictextsms.png'),
	icquadem: require('./imgApp/icquadem.png'),
	iccheckinnhieulan: require('./imgApp/iccheckinnhieulan.png'),
	icdemmuon: require('./imgApp/icdemmuon.png'),

	icBe1: require('./imgApp/icBe1.png'),
	icBe2: require('./imgApp/icBe2.png'),
	icInfo1: require('./imgApp/icInfo1.png'),
	icPofile: require('./imgApp/icPofile.png'),
	//-- More

	// p: require('./imgApp/p.png'),
	person: require('./imgApp/person.png'),
	thang: require('./imgApp/thang.png'),
	btnNext: require('./imgApp/btnNext.png'),
	btnPre: require('./imgApp/btnPre.png'),
	icShowLessUp: require('./imgApp/icshowLessUp.png'),
	icShowLessDown: require('./imgApp/icShowLessDown.png'),
	icDelCard: require('./imgApp/icDelCard.png'),
	icPlusBlue: require('./imgApp/icPlusBlue.png'),
	//-- icApp loading
	icPhoneGrey: require('./imgApp/icPhoneGrey.png'),
	icPhone: require('./imgApp/icPhone.png'),
	icAvataTest: require('./imgApp/icAvataTest.png'),
	icUserGray: require('./imgApp/icUserGray.png'),

	icProfile: require('./imgApp/icProfile.png'),
	icRightWhite: require('./imgApp/icRightWhite.png'),



	icPayoo: require('./imgApp/icPayoo.png'),
	icVNPay: require('./imgApp/icVNPay.png'),
	icDown: require('./imgApp/icDown.png'),
	icUp: require('./imgApp/icUp.png'),
	//Data1test
	icIcon1: require('./imgApp/icon1.png'),
	icIcon2: require('./imgApp/icon2.png'),
	icIcon3: require('./imgApp/icon3.png'),
	icIcon4: require('./imgApp/icon4.png'),
	icIcon5: require('./imgApp/icon5.png'),

	//ALL LANGUAGES

	//Icnew
	imagesPoint: require('./imgApp/imagesPoint.png'),
	logoPoint: require('./imgApp/logoPoint.png'),
	locPoint: require('./imgApp/locPoint.png'),
	blogLike: require('./imgApp/like.png'),
	blogShare: require('./imgApp/share.png'),
	// abu: require('../images/imgApp/abu.png'),
	ic_Chiase: require('../images/imgApp/ic_Chiase.png'),
	// icActivity: require('./imgApp/icActivity.png'),
	ic_like: require('./imgApp/ic_like.png'),
	imgBorderItemSlider: require('./imgApp/imgBorderItemSlider.png'),
	//ic Tab bar
	icTabBar: require('./imgApp/icTabBar.png'),
	icViDienTu: require('./imgApp/icViDienTu.png'),
	icTripUHome: require('./imgApp/icTripUHome.png'),
	icTinNhan: require('./imgApp/icTinNhan.png'),
	icCuaToi: require('./imgApp/icCuaToi.png'),
	icRefresh: require('./imgApp/icRefresh.png'),

	//Setting
	icPushNoti: require('./imgApp/icPushNoti.png'),
	icStarReview: require('./imgApp/icStarReview.png'),

	//reward
	ic_Chiase: require('./imgApp/ic_Chiase.png'),


	// history
	icMug: require('./imgApp/mug.png'),
	icSingle: require('./imgApp/single.png'),
	icWarning: require('./imgApp/icWarning.png'),
	icUserHistoryDetail: require('./imgApp/userHistoryDetail.png'),

	//suport center
	// FlightSuport: require('./imgApp/FlightSuport.png'),
	// headset: require('./imgApp/headset.png'),
	ic_smile: require('./imgApp/smile.png'),
	// icRoundGroupWork: require('./imgApp/round-group-work.png'),
	icRoundExpandMore: require('./imgApp/round-expand-more.png'),
	// icRoundWork: require('./imgApp/round-work.png'),
	// icRoundWorkBagage: require('./imgApp/round-work-bagage.png'),
	//TOur
	ic_touImage: require('./imgApp/touImage.png'),
	// icAirportTour: require('./imgApp/icAirportTour.png'),
	icRailwayTour: require('./imgApp/icRailwayTour.png'),
	icPersonTour: require('./imgApp/icPersonTour.png'),
	icnextTour: require('./imgApp/icnextTour.png'),
	icRestaurantTour: require('./imgApp/icRestaurantTour.png'),
	// icMoodTour: require('./imgApp/icMoodTour.png'),
	// icLocalHotelTour: require('./imgApp/icLocalHotelTour.png'),
	icWarningTour: require('./imgApp/icWarningTour.png'),
	icCancelTour: require('./imgApp/icCancelTour.png'),

	//flight
	icSkyscanner: require('./imgApp/skyscanner.png'),
	icUserPlus: require('./imgApp/user-plus.png'),

	//visa
	icVerifieduser: require('./imgApp/icverifieduser.png'),
	increase: require('./imgApp/increase.png'),
	//Mamnon
	eGmCpl: require('./imgApp/eGmCpl.png'),
	successBB: require('./imgApp/successBB.png'),
	groupchat1: require('./imgApp/groupchat1.png'),
	groupchat2: require('./imgApp/groupchat2.png'),
	Ungroupchat1: require('./imgApp/Ungroupchat1.png'),
	Ungroupchat2: require('./imgApp/Ungroupchat2.png'),
	imagesIc: require('./imgApp/images.png'),
	icGochocTap: require('./imgApp/icGochocTap.png'),
	icGocHoatDong: require('./imgApp/icGocHoatDong.png'),
	icKhaosat: require('./imgApp/icKhaosat.png'),
	icoCam: require('./imgApp/icoCam.png'),
	icKhac: require('./imgApp/icKhac.png'),
	icUnstarHS: require('./imgApp/icUnstarHS.png'),
	icstarHS: require('./imgApp/icstarHS.png'),
	icLikeGocHD: require('./imgApp/icLikeGocHD.png'),
	icGocHD: require('./imgApp/icGocHD.png'),
	icaddpicture: require('./imgApp/icaddpicture.png'),
	icAddLop: require('./imgApp/icAddLop.png'),
	icnapas: require('./imgApp/napas.png'),
	icCall: require('./imgApp/icCall.png'),
	icViber: require('./imgApp/icViber.png'),
	icZalo: require('./imgApp/icZalo.png'),
	icSkype: require('./imgApp/icSkype.png'),
	icFacebook: require('./imgApp/icFacebook.png'),
	icBook: require('./imgApp/icBook.png'),
	icHoaDon: require('./imgApp/icHoaDon.png'),
	icNapTien: require('./imgApp/icNapTien.png'),
	icTheCao: require('./imgApp/icTheCao.png'),
	icMuaSam: require('./imgApp/icMuaSam.png'),
	icGiaiTri: require('./imgApp/icGiaiTri.png'),
	icDanhBa: require('./imgApp/icDanhBa.png'),
	icMobifone: require('./imgApp/icMobifone.png'),
	icPlus: require('./imgApp/icPlus.png'),
	icMinus: require('./imgApp/icMinus.png'),
	icVinaphone: require('./imgApp/icVinaphone.png'),
	icViettel: require('./imgApp/icViettel.png'),
	icVietnammobile: require('./imgApp/icVietnammobile.png'),
	icGmobile: require('./imgApp/icGmobile.png'),
	icTick: require('./imgApp/icTick.png'),
	icseeAll: require('./imgApp/icseeAll.png'),
	icTTDienThoai: require('./imgApp/icTTDienThoai.png'),
	icTTTienNuoc: require('./imgApp/icTTTienNuoc.png'),
	icTTInternet: require('./imgApp/icTTInternet.png'),
	icTTDien: require('./imgApp/icTTDien.png'),
	icTruyenHinh: require('./imgApp/icTruyenHinh.png'),
	icPhoneCoDinh: require('./imgApp/icPhoneCoDinh.png'),
	icVayTieuDung: require('./imgApp/icVayTieuDung.png'),
	icChungcu: require('./imgApp/icChungcu.png'),
	icThuHocPhi: require('./imgApp/icThuHocPhi.png'),
	icTTKhac: require('./imgApp/icTTKhac.png'),
	icHistory: require('./imgApp/icHistory.png'),
	icCTbaobai: require('./imgApp/icCTbaobai.png'),
	icBaiKiemTra: require('./imgApp/icBaiKiemTra.png'),
	icChiTietLichSu: require('./imgApp/icChiTietLichSu.png'),
	KScheck: require('./imgApp/KScheck.png'),
	KSUncheck: require('./imgApp/KSUncheck.png')
};
